#!/bin/bash

# System Information
hostname=$(hostname)
os=$(cat /etc/os-release)
uptime=$(uptime)

# hardware information
cpu=$(cat /proc/cpuinfo | grep "model name" | uniq)
speed=$(cat /proc/cpuinfo | grep "cpu MHz")
ram=$(free -h)
disk=$(lsblk -d -o NAME,MODEL,SIZE)
video=$(lshw -class display)

# network information
fqdn=$(hostname -f)
hostaddress=$(nslookup $(hostname))
gatewayip=$(ip r | grep default | awk '{print $3}')
dnsserver=$(cat /etc/resolv.conf)
interfacename=$(lshw -class network)
ipaddress=$(ip -o -4 address show scope global | awk '{print $4}')

# system status
user=$(who | awk '{printf "%s%s", sep, $1; sep = ","}')
diskspace=$(df -h)
processcount=$(ps aux | wc -l)
loadaverages=$(uptime | awk -F'[a-z]:' '{print $2}')
memoryallocation=$(free -h | grep Mem | awk '{print $4}')
listeningnetworkports=$(ss -tuln)
ufwrules=$(ufw show numbered)

# output
cat <<EOF

System Report Generated by $(whoami) on $(date)

System Information
------------------
Hostname: $hostname
OS: $os
Uptime: $uptime

Harware Information
-------------------
Cpu: $cpu
Speed: $speed
Ram: $ram
Disk: $disk
Video: $video

Network Information
-------------------
FQDN: $fqdn
Host Address: $hostaddress
Gateway IP: $gatewayip
DNS Server: $dnsserver

Interface Name: $interfacename
IP Address: $ipaddress

System Status
-------------
User Logged In: $user
Disk Space: $diskspace
Process count: $processcount
Load Averages: $loadaverages
Memory Allocation: $memoryallocation
Listening Network Ports: $listeningnetworkports
UFW Rules: $ufwrules

EOF
